- hosts: ansible
  connection: local
  tasks:

  - name: deploy aws_load_balancer
    debug: msg="Deploying load balancer elb-missayuq-qa"

  - name: deploy aws security groups
    no_log: True
    debug: msg="Add TCP port {{ item }}"
    with_items:
    - 8080
    - 3306
    - 80

  - name: deploy aws ec2 instances
    debug: msg="Deploy 2 {{ item }} instances "
    with_items:
    - Application
    - Database

  - name: list aws instances
    debug: msg="{{ item.name }} {{ item.ip }}"
    with_items:
    - 
      name: missayuq-qa-app-01
      ip: 134.45.3.18
    - 
      name: missayuq-qa-app-02
      ip: 134.45.3.25
    - 
      name: missayuq-qa-db-01
      ip: 134.45.3.28

  - name: deploy common software
    debug: msg="Deploying {{ item }}"
    with_items:
    - iftop
    - apachetop
    - htop
    - xfsprogs
    - iotop
    - tcpdump
    - schedtool
    - unzip

- hosts: application-vms
  connection: local
  tasks:

  - name: deploy nginx
    debug: msg="Deploying nginx on {{ item }}"
    with_items:
    - missayuq-app-qa-01
    - missayuq-app-qa-02

  - name: deploy apache
    debug: msg="Deploying apache on {{ item }}"
    with_items:
    - missayuq-app-qa-01
    - missayuq-app-qa-02

  - name: deploy java
    debug: msg="Deploying java on {{ item }}"
    with_items:
    - missayuq-app-qa-01
    - missayuq-app-qa-02

  - name: deploy tomcat
    debug: msg="Deploying tomcat on {{ item }}"
    with_items:
    - missayuq-app-qa-01
    - missayuq-app-qa-02

- hosts: database-vms
  connection: local
  tasks:

  - name: deploy mysql
    debug: msg="Deploying mysql on {{ item }}"
    with_items:
    - missayuq-app-qa-01
    - missayuq-app-qa-02

  - name: create database
    debug: msg="Create database {{ item }}"
    with_items:
    - db_missayuq_qa


  - name: create database users
    debug: msg="Create database users {{ item }}"
    with_items:
    - u_missayuq_qa
    - u_admin_qa
    - u_reandonly_qa
  
- name: load site
    debug: msg="site: http://elb-missayuq-qa:8983/"
    



    