- hosts: ansible
  connection: local
  tasks:
  - name: deploy aws_load_balancer
    debug: msg="Deploying load balancer elb-missayuq-qa"
  - name: deploy aws security groups
    debug: msg="Add TCP port {{ item }}"
    with_items:
    - 8080
    - 3306
    - 80
  - name: deploy aws ec2 instances
    debug: msg="Deploy 2 {{ item }} instances "
    with_items:
    - Application
    - Database
  - name: list aws instances
    debug: msg="{{ item.name }} {{ item.ip }}"
    with_items:
    - 
      name: missayuq-app-01
      ip: 134.45.3.18
    - 
      name: missayuq-app-02
      ip: 134.45.3.25
    - 
      name: missayuq-db-01
      ip: 134.45.3.28

    